services:
  - type: web
    name: transaxion-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: API_KEY
        value: SASCSC-SCASCASCS-SCSCS-ASCATV
